### ISSUE TITLE
v4 release

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/carto.js#2092]
### Tasks

- [x] Merge `v4` to `master`.
- [x] Set `master` as main branch.
- [x] Rename repo to `carto.js`.
- [x] Set version to 4.0.0
- [x] Publish package to `@carto\carto.js`
- [x] Point Builder cdb submodule to "new" repo.
- [x] Review current `cartodb.js` github pages.
- [x] Reviews docs for NPM references.
- [x] Deprecate old `carto.js` npm package.

**Comment by ivanmalagon** [comment]
Release of the fix of links in old documentarion (https://github.com/CartoDB/carto.js/issues/2095)[#2095] is pending.

The PR is merged but there's a problem in the docs deploys.

Apart from that, we can say that v4 has been released successfully!!
